// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-fetch';
import type {
  FeedsGetFeedsError,
  FeedsGetFeedsResponse,
  FeedsSearchData,
  FeedsSearchError,
  FeedsSearchResponse,
  AccountRegisterData,
  AccountRegisterError,
  AccountRegisterResponse,
  AccountLoginData,
  AccountLoginError,
  AccountLoginResponse,
  AccountGetUserError,
  AccountGetUserResponse
} from './types.gen';

export const client = createClient(createConfig());

export const feedsGetFeeds = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<FeedsGetFeedsResponse, FeedsGetFeedsError, ThrowOnError>({
    ...options,
    url: '/api/Feeds'
  });
};

export const feedsSearch = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<FeedsSearchData, ThrowOnError>
) => {
  return (options?.client ?? client).post<FeedsSearchResponse, FeedsSearchError, ThrowOnError>({
    ...options,
    url: '/api/Feeds/search'
  });
};

export const accountRegister = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AccountRegisterData, ThrowOnError>
) => {
  return (options?.client ?? client).post<
    AccountRegisterResponse,
    AccountRegisterError,
    ThrowOnError
  >({
    ...options,
    url: '/api/Account/register'
  });
};

export const accountLogin = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AccountLoginData, ThrowOnError>
) => {
  return (options?.client ?? client).post<AccountLoginResponse, AccountLoginError, ThrowOnError>({
    ...options,
    url: '/api/Account/login'
  });
};

export const accountGetUser = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>
) => {
  return (options?.client ?? client).get<AccountGetUserResponse, AccountGetUserError, ThrowOnError>(
    {
      ...options,
      url: '/api/Account/user'
    }
  );
};
