// This file is auto-generated by @hey-api/openapi-ts

export type ApiResponse = {
  success?: boolean;
  message?: string | null;
  errors?: Array<string> | null;
  hasErrors?: boolean;
};

export type ApiResponseOfUserWithRolesResponse = {
  success?: boolean;
  message?: string | null;
  errors?: Array<string> | null;
  hasErrors?: boolean;
  data?: UserWithRolesResponse | null;
};

export type AuthenticationResponse = ApiResponse & {
  token?: string | null;
  expiration?: string;
};

export type BaseModel = {
  id?: string;
};

export type Feed = BaseModel & {
  title?: string;
  description?: string;
  webUrl?: string;
  feedUrl?: string;
  imageUrl?: string | null;
  language?: string | null;
  categories?: Array<string>;
  items?: Array<FeedItem>;
  searchVector?: Array<Lexeme> | null;
};

export type FeedItem = BaseModel & {
  title?: string;
  plainTextContent?: string | null;
  htmlContent?: string | null;
  url?: string;
  summary?: string | null;
  imageUrl?: string | null;
  published?: string;
  author?: string | null;
  categories?: Array<string>;
  feedId?: string;
  feed?: Feed;
  searchVector?: Array<Lexeme> | null;
};

export type ItemResponse = {
  id?: string;
  title?: string;
  plainTextContent?: string | null;
  htmlContent?: string | null;
  url?: string;
  summary?: string | null;
  imageUrl?: string | null;
  published?: string;
  author?: string | null;
  feedId?: string;
  categories?: Array<string>;
};

export type Lexeme = {
  text?: string;
  count?: number;
};

export type LoginUserRequest = {
  email: string;
  password: string;
};

export type ProblemDetails = {
  type?: string | null;
  title?: string | null;
  status?: number | null;
  detail?: string | null;
  instance?: string | null;
  [key: string]: ((unknown | string | number) | null) | undefined;
};

export type RegisterUserRequest = {
  name: string;
  email: string;
  password: string;
  passwordConfirmation: string;
};

export type SearchResponse = {
  count?: number;
  items?: Array<ItemResponse>;
};

export type UserWithRolesResponse = {
  name?: string;
  email?: string;
  roles?: Array<string>;
};

export type FeedsGetFeedsResponse = Array<Feed>;

export type FeedsGetFeedsError = unknown;

export type FeedsSearchData = {
  query?: {
    searchTerm?: string;
  };
};

export type FeedsSearchResponse = SearchResponse;

export type FeedsSearchError = ProblemDetails;

export type AccountRegisterData = {
  body: RegisterUserRequest;
};

export type AccountRegisterResponse = ApiResponse;

export type AccountRegisterError = unknown;

export type AccountLoginData = {
  body: LoginUserRequest;
};

export type AccountLoginResponse = AuthenticationResponse;

export type AccountLoginError = unknown;

export type AccountGetUserResponse = ApiResponseOfUserWithRolesResponse;

export type AccountGetUserError = unknown;
