@HostAddress = http://localhost:5050

### POST request to register user
# @name Register
POST {{HostAddress}}/register
Content-Type: application/json

{
  "name": "Jeff Caldwell",
  "email": "jeff.caldwell@intellivega.com",
  "password": "Password123!",
  "passwordConfirmation": "Password123!"
}
###

### POST request to log in user
# @name Login
POST {{HostAddress}}/login
Content-Type: application/json

{
  "email": "jeff.caldwell@intellivega.com",
  "password": "Password123!"
}
###

### GET request to logout user
# @name Logout
GET {{HostAddress}}/logout
Accept: application/json
###