### POST request to register user
POST http://localhost:5050/api/account/register
Content-Type: application/json

{
  "name": "Mister Test",
  "email": "test@test.com",
  "password": "Password123!"
}
###